version: "3.9"

networks:
  neutrino-net:
    driver: bridge

services:

  web:
    image:  ghcr.io/wcherry/neutrino.app/web:sha-45769fc
    extra_hosts:
       - "host.docker.internal:host-gateway"
    container_name: neutrino-nginx-proxy
    networks:
      - neutrino-net
    ports:
      - "9080:8080"
    volumes:
      - ./neutrino-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  auth:
    image:  ghcr.io/wcherry/neutrino.app/auth:sha-45769fc
    container_name: neutrino-auth-service
    networks:
      - neutrino-net
    environment:
      JWT_SECRET: your-secret-key-here-change-in-production
      JWT_ACCESS_EXPIRY_SECS: 900
      JWT_REFRESH_EXPIRY_SECS: 604800
      AUTH_DATABASE_URL: /usr/local/data/auth.db
      AUTH_PORT: 8080
      LOG_PATH: /usr/local/logs/
      LOG_LEVEL: debug    
    volumes:
      - ./logs/auth:/usr/local/logs
      - ./data/auth:/usr/local/data


  drive:
    image:  ghcr.io/wcherry/neutrino.app/drive:sha-45769fc
    container_name: neutrino-drive-service
    networks:
      - neutrino-net
    environment:
      JWT_SECRET: your-secret-key-here-change-in-production
      JWT_ACCESS_EXPIRY_SECS: 900
      JWT_REFRESH_EXPIRY_SECS: 604800
      LOG_LEVEL: debug
      AUTH_URL: http://auth:8080/
      DRIVE_DATABASE_URL: /usr/local/data/drive.db
      DRIVE_PORT: 8080
      STORAGE_PATH: /usr/local/data/storage
      LOG_PATH: /usr/local/logs/
    volumes:
      - ./logs/drive:/usr/local/logs
      - ./data/drive:/usr/local/data
    

  worker:
    container_name: neutrino-worker
    image: ghcr.io/wcherry/neutrino.app/worker:sha-45769fc
